name: Training and Docker Build Pipeline

on:
  push:
    branches:
      - staging

jobs:
  train-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the training script
    - name: Run training script
      run: |
        python training.py

    # Step 5: Upload trained model as an artifact
    - name: Upload trained model as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: model
        path: model.pkl

    # Step 6: Log in to Azure
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 7: Log in to Azure Container Registry (ACR)
    - name: Log in to ACR
      run: |
        az acr login --name <your-acr-name>

    # Step 8: Build and push Docker image to ACR
    - name: Build and push Docker image
      run: |
        docker build -t <your-acr-name>.azurecr.io/fastapi-app:latest .
        docker push <your-acr-name>.azurecr.io/fastapi-app:latest
